
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR rv32imac)

set(TOOLCHAIN_TRIPLET "riscv-none-embed")
set(CMAKE_LIBRARY_ARCHITECTURE riscv-none-embed)

set(_EMBED_VERSION "v1.4")


# Always use RISCV_TOOLCHAIN_DIR if set, no fallback!
if(DEFINED ENV{RISCV_TOOLCHAIN_DIR} AND NOT "$ENV{RISCV_TOOLCHAIN_DIR}" STREQUAL "")
    set(_EMBED_BIN_DIR "$ENV{RISCV_TOOLCHAIN_DIR}/bin")
    message(STATUS "Using RISCV_TOOLCHAIN_DIR from environment: $_EMBED_BIN_DIR")
    # Accept any riscv *-gcc binary present in the bin dir (covers riscv64-unknown-elf-gcc, riscv-none-elf-gcc, etc.)
    file(GLOB _CAND_GCC LIST_DIRECTORIES false "${_EMBED_BIN_DIR}/*-gcc*")
    if(_CAND_GCC)
        list(SORT _CAND_GCC)
        list(GET _CAND_GCC 0 _GCC_EXE)
        message(STATUS "Found compiler in RISCV_TOOLCHAIN_DIR: ${_GCC_EXE}")
    else()
        # fallback to specific known names
        if(WIN32)
            set(_GCC_EXE "${_EMBED_BIN_DIR}/riscv-none-embed-gcc.exe")
            set(_ALT_GCC_EXE "${_EMBED_BIN_DIR}/riscv-none-elf-gcc.exe")
        else()
            set(_GCC_EXE "${_EMBED_BIN_DIR}/riscv-none-embed-gcc")
            set(_ALT_GCC_EXE "${_EMBED_BIN_DIR}/riscv-none-elf-gcc")
        endif()
        if(NOT EXISTS "${_GCC_EXE}" AND EXISTS "${_ALT_GCC_EXE}")
            set(_GCC_EXE "${_ALT_GCC_EXE}")
            message(STATUS "RISCV_TOOLCHAIN_DIR provided but embed-named GCC not found; using elf-named compiler: ${_GCC_EXE}")
        elseif(NOT EXISTS "${_GCC_EXE}")
            file(GLOB _BIN_CONTENTS LIST_DIRECTORIES false "${_EMBED_BIN_DIR}/*")
            message(FATAL_ERROR "RISCV_TOOLCHAIN_DIR is set, but no suitable riscv gcc found in ${_EMBED_BIN_DIR}!\nContents of bin dir:\n${_BIN_CONTENTS}")
        endif()
lse()
    # Prefer any local 'riscv-none-embed-gcc-*' installed under dependencies/tools/risc
    file(GLOB _LOCAL_EMBED_DIRS RELATIVE "${CMAKE_CURRENT_LIST_DIR}/../../tools/risc" "${CMAKE_CURRENT_LIST_DIR}/../../tools/risc/riscv-none-embed-gcc-*")
    if(_LOCAL_EMBED_DIRS)
        list(SORT _LOCAL_EMBED_DIRS)
        list(REVERSE _LOCAL_EMBED_DIRS)
        list(GET _LOCAL_EMBED_DIRS 0 _LOCAL_CHOICE)
        set(_EMBED_BIN_DIR "${CMAKE_CURRENT_LIST_DIR}/../../tools/risc/${_LOCAL_CHOICE}/bin")
    else()
        set(CMAKE_SYSTEM_NAME Generic)
        set(CMAKE_SYSTEM_VERSION 1)
        set(CMAKE_SYSTEM_PROCESSOR rv32imac)

        set(TOOLCHAIN_TRIPLET "riscv-none-embed")
        set(CMAKE_LIBRARY_ARCHITECTURE riscv-none-embed)

        # Pinned toolchain: use the specific local path only
        set(_PINNED_TOOLCHAIN_ROOT "D:/git/dependencies/tools/risc/riscv-toolchain/risc-none-embed-gcc-8.2.0")
        if(WIN32)
            set(_GCC_EXE "${_PINNED_TOOLCHAIN_ROOT}/bin/riscv-none-embed-gcc.exe")
        else()
            set(_GCC_EXE "${_PINNED_TOOLCHAIN_ROOT}/bin/riscv-none-embed-gcc")
        endif()

        if(EXISTS "${_GCC_EXE}")
            get_filename_component(TOOLCHAIN_DIR "${_PINNED_TOOLCHAIN_ROOT}" ABSOLUTE)
            set(_EMBED_BIN_DIR "${_PINNED_TOOLCHAIN_ROOT}/bin")
            message(STATUS "Using pinned riscv toolchain: ${TOOLCHAIN_DIR}")
        else()
            message(FATAL_ERROR "Pinned RISC-V toolchain not found at: ${_PINNED_TOOLCHAIN_ROOT}\nPlease install the toolchain at that path.")
        endif()
else()
    set(CMAKE_LIBRARY_ARCHITECTURE "riscv-none-embed")
    message(STATUS "Using CMAKE_LIBRARY_ARCHITECTURE=${CMAKE_LIBRARY_ARCHITECTURE} (detected from ${_GCC_EXE})")
endif()

include(${CMAKE_CURRENT_LIST_DIR}/gcc.cmake)
