
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR rv32imac)

set(TOOLCHAIN_TRIPLET "riscv-none-embed")
set(CMAKE_LIBRARY_ARCHITECTURE riscv-none-embed)

set(_EMBED_VERSION "v1.4")


# Always use RISCV_TOOLCHAIN_DIR if set, no fallback!
if(DEFINED ENV{RISCV_TOOLCHAIN_DIR} AND NOT "$ENV{RISCV_TOOLCHAIN_DIR}" STREQUAL "")
    set(_EMBED_BIN_DIR "$ENV{RISCV_TOOLCHAIN_DIR}/bin")
    message(STATUS "Using RISCV_TOOLCHAIN_DIR from environment: $_EMBED_BIN_DIR")
    if(WIN32)
        set(_GCC_EXE "${_EMBED_BIN_DIR}/riscv-none-embed-gcc.exe")
    else()
        set(_GCC_EXE "${_EMBED_BIN_DIR}/riscv-none-embed-gcc")
    endif()
    if(NOT EXISTS "${_GCC_EXE}")
            # If embed-named GCC isn't present, accept an xPack 'elf' binary as a fallback
            if(WIN32)
                set(_ALT_GCC_EXE "${_EMBED_BIN_DIR}/riscv-none-elf-gcc.exe")
            else()
                set(_ALT_GCC_EXE "${_EMBED_BIN_DIR}/riscv-none-elf-gcc")
            endif()
            if(EXISTS "${_ALT_GCC_EXE}")
                set(_GCC_EXE "${_ALT_GCC_EXE}")
                message(STATUS "RISCV_TOOLCHAIN_DIR provided but embed-named GCC not found; using elf-named compiler: ${_GCC_EXE}")
            else()
                file(GLOB _BIN_CONTENTS LIST_DIRECTORIES false "${_EMBED_BIN_DIR}/*")
                message(FATAL_ERROR "RISCV_TOOLCHAIN_DIR is set, but ${_GCC_EXE} not found!\nContents of bin dir:\n${_BIN_CONTENTS}")
            endif()
    endif()
else()
    # Prefer any local 'riscv-none-embed-gcc-*' installed under dependencies/tools/risc
    file(GLOB _LOCAL_EMBED_DIRS RELATIVE "${CMAKE_CURRENT_LIST_DIR}/../../tools/risc" "${CMAKE_CURRENT_LIST_DIR}/../../tools/risc/riscv-none-embed-gcc-*")
    if(_LOCAL_EMBED_DIRS)
        list(SORT _LOCAL_EMBED_DIRS)
        list(REVERSE _LOCAL_EMBED_DIRS)
        list(GET _LOCAL_EMBED_DIRS 0 _LOCAL_CHOICE)
        set(_EMBED_BIN_DIR "${CMAKE_CURRENT_LIST_DIR}/../../tools/risc/${_LOCAL_CHOICE}/bin")
    else()
        # Fallback: xPack or default
        file(GLOB _XP_PACKS RELATIVE "${CMAKE_CURRENT_LIST_DIR}/../../tools/risc" "${CMAKE_CURRENT_LIST_DIR}/../../tools/risc/xpack-riscv-none-elf-gcc-*")
        if(_XP_PACKS)
            list(SORT _XP_PACKS)
            list(GET _XP_PACKS 0 _CHOICE)
            set(_EMBED_BIN_DIR "${CMAKE_CURRENT_LIST_DIR}/../../tools/risc/${_CHOICE}/bin")
        else()
            set(_EMBED_BIN_DIR "${CMAKE_CURRENT_LIST_DIR}/../../tools/risc/riscv-none-embed-gcc-${_EMBED_VERSION}/bin")
        endif()
    endif()
endif()

    # Detect any riscv *-gcc binary in the bin directory (covers riscv-none-*, riscv64-unknown-elf-*, etc.)
    file(GLOB _GCC_CANDS LIST_DIRECTORIES false "${_EMBED_BIN_DIR}/*-gcc*")
    if(_GCC_CANDS)
        list(SORT _GCC_CANDS)
        list(GET _GCC_CANDS 0 _GCC_EXE)
        message(STATUS "Using detected compiler: ${_GCC_EXE}")
    else()
        # Try to find riscv-none-embed-gcc on PATH as a fallback
        find_program(_FOUND_RISCV_GCC riscv-none-embed-gcc)
        if(_FOUND_RISCV_GCC)
            get_filename_component(_FOUND_BIN_DIR "${_FOUND_RISCV_GCC}" DIRECTORY)
            set(_EMBED_BIN_DIR "${_FOUND_BIN_DIR}")
            file(GLOB _GCC_CANDS LIST_DIRECTORIES false "${_EMBED_BIN_DIR}/*-gcc*")
            if(_GCC_CANDS)
                list(SORT _GCC_CANDS)
                list(GET _GCC_CANDS 0 _GCC_EXE)
                message(STATUS "Found riscv compiler on PATH: ${_GCC_EXE}")
            endif()
        endif()

        # Try xPack toolchain path if XPACK_RISCV_VERSION env var is set (CI cache)
        if(NOT DEFINED _GCC_EXE AND DEFINED ENV{XPACK_RISCV_VERSION} AND NOT "" STREQUAL "$ENV{XPACK_RISCV_VERSION}")
            set(_XPACK_DIR "${CMAKE_CURRENT_LIST_DIR}/../../tools/risc/xpack-riscv-none-elf-gcc-$ENV{XPACK_RISCV_VERSION}")
            file(GLOB _GCC_CANDS LIST_DIRECTORIES false "${_XPACK_DIR}/bin/*-gcc*")
            if(_GCC_CANDS)
                list(SORT _GCC_CANDS)
                list(GET _GCC_CANDS 0 _GCC_EXE)
                set(_EMBED_BIN_DIR "${_XPACK_DIR}/bin")
                message(STATUS "Found xpack riscv toolchain: ${_GCC_EXE}")
            endif()
        endif()

        if(NOT DEFINED _GCC_EXE)
            file(GLOB _BIN_CONTENTS LIST_DIRECTORIES false "${_EMBED_BIN_DIR}/*")
            message(FATAL_ERROR "riscv compiler not found in toolchain bin dir: ${_EMBED_BIN_DIR}\nContents of bin dir:\n${_BIN_CONTENTS}")
        endif()
    endif()

get_filename_component(TOOLCHAIN_DIR "${_EMBED_BIN_DIR}/.." ABSOLUTE)
message(STATUS "Found riscv-none-embed toolchain: ${TOOLCHAIN_DIR}")

# Adjust library architecture prefix to match detected toolchain binaries
if(_GCC_EXE MATCHES "elf")
    set(CMAKE_LIBRARY_ARCHITECTURE "riscv-none-elf")
    message(STATUS "Using CMAKE_LIBRARY_ARCHITECTURE=${CMAKE_LIBRARY_ARCHITECTURE} (detected from ${_GCC_EXE})")
else()
    set(CMAKE_LIBRARY_ARCHITECTURE "riscv-none-embed")
    message(STATUS "Using CMAKE_LIBRARY_ARCHITECTURE=${CMAKE_LIBRARY_ARCHITECTURE} (detected from ${_GCC_EXE})")
endif()

include(${CMAKE_CURRENT_LIST_DIR}/gcc.cmake)
